### ISSUE TITLE
Failed to get frame when use dds with docker after the machine restart

### ISSUE THREAD

**Issue by ledinhtri97** [IDEA-Research/deepdataspace#104]
Thank you for the great work!

I had face this bug when try to restart machine. It seem the dds could not load previous dataset had saved before. 

```
2023-11-09 09:07:56,428 INFO [django.server] "GET /api/v1/datasets?page_num=1&page_size=50 HTTP/1.1" 200 433
2023-11-09 09:07:56,441 ERROR [django.request] Internal Server Error: /files/local_files/b/1/-1_-1/image_png//dds/datasets/test_data_ann/sub1/2.png
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 624, in connect
    sock = self.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 625, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 658, in _connect
    for res in socket.getaddrinfo(
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/dds/source/./deepdataspace/server/resources/files/local_file.py", line 65, in read_file
    if not Redis.sismember(RedisKey.DatasetImageDirs, file_dir):
  File "/usr/local/lib/python3.10/site-packages/redis/commands/core.py", line 3340, in sismember
    return self.execute_command("SISMEMBER", name, value)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 1427, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 630, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
2023-11-09 09:07:56,441 ERROR [django.request] Internal Server Error: /files/local_files/b/1/-1_-1/image_png//dds/datasets/test_data_ann/sub1/2.png
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 624, in connect
    sock = self.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 625, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 658, in _connect
    for res in socket.getaddrinfo(
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:
```

**Comment by imhuwq** [comment]
Hi @ledinhtri97 , sorry for the late response.
It's a redis connection error.
Can you give me the full start up logs here?

**Comment by imhuwq** [comment]
Hi @ledinhtri97, we're temporarily closing this issue due to inactivity. However, please don't hesitate to reach out to us if you encounter any further problems or have questions in the future.
